INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (2,"Nutrition and dietetics",38);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (3,"Diagnostic imaging",75);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (4,"Neonatal unit",42);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (5,"Gynaecology",57);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (6,"Ear nose and throat",58);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (7,"Nephrology",57);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (8,"Microbiology",62);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (9,"Accident and Emergency",16);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (10,"Microbiology",88);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (11,"Orthopaedics",94);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (12,"Accident and Emergency",59);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (13,"Neurology",14);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (14,"Maternity departments",83);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (15,"Maternity departments",59);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (16,"Cardiology",74);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (17,"Ear nose and throat",31);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (18,"Critical care",92);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (19,"Neurology",87);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (20,"Ophthalmology",58);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (21,"Neurology",61);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (22,"Ophthalmology",9);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (23,"Breast screening",75);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (24,"Gastroenterology",38);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (25,"Haematology",7);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (26,"Maternity departments",18);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (27,"Anaesthetics",44);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (28,"Occupational therapy",34);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (29,"Accident and Emergency",97);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (30,"Anaesthetics",11);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (31,"Nephrology",20);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (32,"Critical care",59);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (33,"Neonatal unit",57);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (34,"Critical care",63);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (35,"Anaesthetics",52);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (36,"Ophthalmology",82);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (37,"Anaesthetics",36);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (38,"Cardiology",43);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (39,"Gynaecology",30);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (40,"Gynaecology",5);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (41,"Nutrition and dietetics",24);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (42,"Accident and Emergency",47);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (43,"Breast screening",8);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (44,"Critical care",34);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (45,"Cardiology",14);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (46,"Diagnostic imaging",94);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (47,"Occupational therapy",98);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (48,"Nephrology",95);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (49,"Nutrition and dietetics",79);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (50,"General surgery",88);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (51,"Gynaecology",6);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (52,"Ear nose and throat",65);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (53,"Orthopaedics",18);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (54,"Critical care",35);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (55,"Ophthalmology",35);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (56,"Gastroenterology",6);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (57,"Orthopaedics",18);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (58,"Accident and Emergency",77);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (59,"Nutrition and dietetics",1);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (60,"Nephrology",18);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (61,"Critical care",32);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (62,"Ear nose and throat",41);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (63,"Nephrology",61);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (64,"Diagnostic imaging",100);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (65,"Orthopaedics",86);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (66,"Ophthalmology",66);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (67,"Accident and Emergency",65);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (68,"Neurology",78);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (69,"Anaesthetics",14);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (70,"Gynaecology",52);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (71,"Anaesthetics",68);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (72,"Ear nose and throat",46);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (73,"Gastroenterology",4);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (74,"Microbiology",16);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (75,"Neurology",50);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (76,"Orthopaedics",24);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (77,"Cardiology",21);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (78,"Neurology",58);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (79,"Neurology",31);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (80,"Haematology",85);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (81,"Breast screening",82);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (82,"Nephrology",14);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (83,"Orthopaedics",12);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (84,"Gastroenterology",34);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (85,"Ophthalmology",30);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (86,"Ophthalmology",39);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (87,"Ear nose and throat",33);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (88,"Haematology",65);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (89,"General surgery",38);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (90,"General surgery",70);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (91,"Haematology",91);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (92,"Gynaecology",63);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (93,"Oncology",67);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (94,"Diagnostic imaging",6);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (95,"Neonatal unit",55);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (96,"Ophthalmology",91);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (97,"Critical care",76);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (98,"Microbiology",37);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (99,"Haematology",2);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (100,"Anaesthetics",67);
INSERT INTO department (departmentID,departmentName,hospitalID) VALUES (101,"Gastroenterology",78);
