INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (2,"Blossom Community Hospital","9471 Mi Ave",258);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (3,"Ruby Valley Hospital Center","2506 Orci. Rd.",74);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (4,"Pine Valley Hospital","Ap #783-6853 Dictum Ave",274);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (5,"Angelstone General Hospital","P.O. Box 923, 2989 Laoreet Rd.",72);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (6,"Green Hill General Hospital","P.O. Box 147, 3075 Dictum Avenue",186);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (7,"Flowerhill General Hospital","265-4202 Consectetuer Ave",435);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (8,"Green Hill General Hospital","916-8045 Dolor St.",488);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (9,"Heart Center Community Hospital","418-5130 Sociis Rd.",93);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (10,"Specialty General Hospital","Ap #603-7875 Facilisis Rd.",88);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (11,"Flowerhill General Hospital","Ap #978-262 Hymenaeos. Ave",234);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (12,"Flowerhill General Hospital","5242 Amet, Street",298);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (13,"Stillwater Clinic","9340 Pellentesque Ave",477);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (14,"Eden Hospital Center","Ap #873-3189 Nec Rd.",94);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (15,"Snowflake Clinic","722-7247 Quam, Avenue",103);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (16,"Fortuna Community Hospital","9221 Eget, Avenue",423);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (17,"Green Hill General Hospital","P.O. Box 355, 6105 Adipiscing Rd.",228);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (18,"Heart Center Community Hospital","P.O. Box 132, 5016 Vel, Av.",215);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (19,"Flowerhill General Hospital","P.O. Box 833, 9362 Mauris Av.",266);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (20,"Snowflake Clinic","P.O. Box 636, 3587 Hendrerit Road",362);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (21,"Good Samaritan Medical Center","Ap #806-2534 Tristique Street",68);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (22,"Snowflake Clinic","5938 Elit Av.",451);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (23,"Pine Valley Hospital","Ap #625-1212 Curabitur Rd.",350);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (24,"White Blossom Medical Clinic","6946 Molestie Rd.",317);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (25,"Stillwater Clinic","P.O. Box 833, 9628 Tincidunt Avenue",473);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (26,"Pine Valley Hospital","P.O. Box 359, 3512 Diam. Av.",337);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (27,"Green Hill General Hospital","3527 Aliquet Ave",365);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (28,"Blossom Community Hospital","3802 Tellus Rd.",492);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (29,"Blossom Valley Medical Center","9229 Orci Road",163);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (30,"White Blossom Medical Clinic","Ap #343-9658 Libero. Ave",211);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (31,"Snowflake Clinic","Ap #243-948 Libero. Street",105);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (32,"Harmony Grove Hospital Center","7779 Nulla Ave",489);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (33,"Specialty General Hospital","797-6183 Tellus. Ave",53);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (34,"Eden Hospital Center","Ap #299-7630 Etiam Ave",200);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (35,"Ruby Valley Hospital Center","2161 Neque. Rd.",365);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (36,"Ruby Valley Hospital Center","643-339 Velit. Ave",317);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (37,"Specialty General Hospital","302-2504 Sed Av.",284);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (38,"Blossom Community Hospital","Ap #583-7833 A St.",258);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (39,"Fortuna Community Hospital","5047 Turpis St.",275);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (40,"Good Samaritan Medical Center","1722 Ut Av.",305);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (41,"Angelstone General Hospital","Ap #468-3985 Vitae St.",338);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (42,"Green Hill General Hospital","630-521 In Avenue",74);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (43,"Green Hill General Hospital","1439 Cursus. Road",142);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (44,"Stillwater Clinic","6322 In Ave",281);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (45,"Green Hill General Hospital","Ap #730-2047 Mattis Rd.",129);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (46,"Blossom Community Hospital","Ap #402-4681 Nunc Av.",87);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (47,"Eden Hospital Center","396-6535 Enim, St.",197);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (48,"Green Hill General Hospital","P.O. Box 708, 6401 Et, Av.",72);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (49,"Fortuna Community Hospital","875-5679 Eu Avenue",469);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (50,"Ruby Valley Hospital Center","5498 Pellentesque Street",439);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (51,"Blossom Valley Medical Center","Ap #434-313 Facilisi. Avenue",419);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (52,"Ruby Valley Hospital Center","P.O. Box 226, 4829 Fames St.",412);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (53,"Harmony Grove Hospital Center","960-4753 Scelerisque Rd.",341);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (54,"Evergreen Hospital Center","714 Aliquam St.",139);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (55,"Flowerhill General Hospital","992-7605 Lobortis, St.",478);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (56,"Specialty General Hospital","P.O. Box 938, 9835 Nullam St.",303);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (57,"Blossom Community Hospital","P.O. Box 201, 5393 Fringilla Rd.",310);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (58,"Stillwater Clinic","476-4309 Ligula. Ave",349);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (59,"Fortuna Community Hospital","557-2607 Aenean St.",147);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (60,"Fairbanks Clinic","P.O. Box 342, 8602 Quisque St.",368);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (61,"White Blossom Medical Clinic","9662 Fusce St.",362);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (62,"Stillwater Clinic","P.O. Box 995, 9003 Cursus Rd.",60);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (63,"Stillwater Clinic","556-1585 Dui. Ave",447);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (64,"Eden Hospital Center","697-2239 Risus. Rd.",325);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (65,"Green Hill General Hospital","8109 Maecenas Rd.",177);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (66,"Heart Center Community Hospital","3081 Diam Rd.",171);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (67,"Overlook Medical Center","2353 Eget Rd.",90);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (68,"Pine Valley Hospital","8149 Sed Av.",120);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (69,"Blossom Valley Medical Center","729-6793 Interdum Street",462);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (70,"Ruby Valley Hospital Center","P.O. Box 989, 2535 Eu Street",65);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (71,"Specialty General Hospital","682-4292 Cras Av.",152);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (72,"Evergreen Hospital Center","865-1921 Leo, Rd.",367);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (73,"Angelstone General Hospital","Ap #159-3156 Sed St.",248);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (74,"Good Samaritan Medical Center","Ap #732-4188 Magna Rd.",377);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (75,"White Blossom Medical Clinic","289-4153 Iaculis, St.",454);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (76,"Snowflake Clinic","1822 Duis Road",116);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (77,"Overlook Medical Center","Ap #344-4226 Eget Rd.",165);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (78,"Eden Hospital Center","P.O. Box 168, 2588 Eleifend Road",284);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (79,"Fairbanks Clinic","Ap #341-8572 Sit St.",473);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (80,"Eden Hospital Center","7201 Mollis Road",293);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (81,"Ruby Valley Hospital Center","Ap #996-6473 Donec Avenue",408);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (82,"Ruby Valley Hospital Center","5778 Non Rd.",70);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (83,"Blossom Community Hospital","1171 Eleifend Ave",397);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (84,"Snowflake Clinic","145-9080 Orci. Avenue",287);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (85,"Specialty General Hospital","Ap #774-9494 Auctor Ave",89);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (86,"Angelstone General Hospital","615-6938 Semper, St.",405);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (87,"Eden Hospital Center","3293 Ante St.",205);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (88,"Eden Hospital Center","7956 Interdum Ave",280);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (89,"Fairbanks Clinic","P.O. Box 252, 9641 Id, Av.",179);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (90,"White Blossom Medical Clinic","579-8511 Ac Av.",215);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (91,"Stillwater Clinic","Ap #482-1390 Inceptos Street",388);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (92,"Green Hill General Hospital","309-4615 Duis Av.",444);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (93,"Specialty General Hospital","P.O. Box 895, 8759 Id, Rd.",98);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (94,"Fortuna Community Hospital","Ap #532-4342 Ad St.",333);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (95,"White Blossom Medical Clinic","P.O. Box 649, 8283 Magnis Rd.",473);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (96,"Good Samaritan Medical Center","Ap #740-5586 Lectus Road",480);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (97,"Ruby Valley Hospital Center","8224 Eget Rd.",274);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (98,"Flowerhill General Hospital","Ap #563-7607 Phasellus St.",445);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (99,"Overlook Medical Center","Ap #233-2965 Facilisis Rd.",365);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (100,"Snowflake Clinic","Ap #733-8326 Sed Rd.",360);
INSERT INTO hospital (hospitalID,hospitalName,address,capacity) VALUES (101,"Flowerhill General Hospital","598-4173 Faucibus St.",149);
